name: Continuous Integration
on:
  pull_request:
    branches:
      - master

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Install dependencies
      - run: |
          cd spotlight
          npm ci

      - name: Run ESLint
      - run: |
          cd spotlight
          eslint . --ext .js,.jsx,.ts,.tsx
